AWSTemplateFormatVersion: 2010-09-09
Description: >-
  incoming-email

Transform:
- AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs20.x
    Architectures:
      - arm64
    VpcConfig:
      SecurityGroupIds:
        - sg-022d777129fddf499
      SubnetIds:
        - subnet-007314cfc0f3c0015
        - subnet-08cb884b95d9da694
    Environment:
      Variables:
        DB_HOST: central-db.cqcgwq24flgj.us-east-1.rds.amazonaws.com
        DB_PORT: 3306
        DB_NAME: dmarc2
        DB_SECRET_NAME: arn:aws:secretsmanager:us-east-1:490387937525:secret:rds!db-acadcb8b-7e88-4088-9336-3ff6aaf0350d-WPzWMv

Resources:
  SNSPayloadLogger:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      Handler: src/handlers/sns-payload-logger.snsPayloadLoggerHandler
      MemorySize: 512
      Timeout: 100
      Policies:
        - AWSLambdaBasicExecutionRole
        - arn:aws:iam::490387937525:policy/lambdaCreateNetworkInterface
        - arn:aws:iam::490387937525:policy/devDbSecretAccess
