AWSTemplateFormatVersion: 2010-09-09
Description: >-
  incoming-email

Transform:
- AWS::Serverless-2016-10-31

Resources:
  SNSPayloadLogger:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs20.x
      Architectures:
        - arm64
      Handler: src/handlers/sns-payload-logger.snsPayloadLoggerHandler
      MemorySize: 512
      Timeout: 100
      Policies:
        # Give Lambda basic execution Permission to the helloFromLambda
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          DB_HOST: dev-db.cqcgwq24flgj.us-east-1.rds.amazonaws.com
          DB_PASSWORD: REPLACE_ME
          DB_PORT: 3306
          DB_USER: admin
