version: 0.2

cache:
  paths:
    - web/node_modules/**/*
    - web/.next/cache/**/*
phases:
  install:
    commands:
      - cd web
      # Install all dependencies (including dependencies for running tests)
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  type: zip
  files:
    - web/out/**/*
