version: 0.2

phases:
  install:
    commands:
      # Install all dependencies (including dependencies for running tests)
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  type: zip
  files:
    - out/*
